/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
  kotlin("jvm") version "1.9.10"
  java
  application
}
application {
  mainClass.set("Window")
}
repositories {
  mavenCentral()
}
dependencies {
  implementation("com.squareup.okhttp3:okhttp:4.10.0")
  implementation("com.google.code.gson:gson:2.9.0")
  implementation ("com.fasterxml.jackson.core:jackson-databind:2.13.0")
  implementation("com.microsoft.cognitiveservices.speech:client-jar-sdk:1.14.0")

}
tasks.register<JavaExec>("run") {
    dependsOn("classes")
    main = mainClass.get()
    classpath = sourceSets["main"].runtimeClasspath
}
