
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class TranslatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form Translator
     */
    private final Translator translator;
    private String Vietnamese;
    private String English;
    public TranslatorWindow() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        translator = new Translator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        TransVietToEn = new javax.swing.JButton();
        TransEnToViet = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Translator");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTextField1.setToolTipText("Type your sentences here...");

        TransVietToEn.setText("Translate Vietnamese to English");
        TransVietToEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransVietToEnActionPerformed(evt);
            }
        });

        TransEnToViet.setText("Translate English to Vietnamese");
        TransEnToViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransEnToVietActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(TransVietToEn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(TransEnToViet)
                .addGap(116, 116, 116))
            .addComponent(jTextField1)
            .addComponent(jTextField2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransVietToEn)
                    .addComponent(TransEnToViet))
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransVietToEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransVietToEnActionPerformed
        // TODO add your handling code here:
        Vietnamese = jTextField1.getText();
        try {
            English = translator.EnToViet(Vietnamese);
            English = translator.prettify(English);
            English = translator.JsonParsing(English);
            jTextField2.setText(English);
        } catch(IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_TransVietToEnActionPerformed

    private void TransEnToVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransEnToVietActionPerformed
        // TODO add your handling code here:
        English = jTextField1.getText();
        try {
            Vietnamese = translator.VietToEn(English);
            Vietnamese = translator.prettify(Vietnamese);
            Vietnamese = translator.JsonParsing(Vietnamese);
            jTextField2.setText(Vietnamese);
        } catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TransEnToVietActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransEnToViet;
    private javax.swing.JButton TransVietToEn;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
